name: Install and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps: 

      - name: Install quig
        run: |
          sudo curl -Ls https://github.com/ijlyttle/quig/releases/latest/download/quig.tar.gz |
            sudo tar xz -C /opt
          sudo ln -sf /opt/quig/bin/quig /usr/local/bin/quig
        
      - name: Install quarto
        run: |
          quig add release
          quarto --version
