on:  
  push:
    tags: "*"
  pull-request: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build tarball
        run: |
          ls -l


