name: Release and Upload

on:  
  push:
    tags: 
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create release
        id: create-release
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const fs = require("fs");

            const tag = context.ref.replace("refs/tags/", "");
            const response = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `${tag}`,
              name: `${context.repo.repo} ${tag.replace(/^v/, "")}`,
              target_commitish: context.sha,
              body: ""
            });

            const result = response.data.id;
            console.log(result);

            return result;

      - name: Upload artifact
        run: |
          echo "release_id: ${{ steps.create-release.outputs.release_id }}"

