on:  
  push:
    tags: ["*"]
  pull_request: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build tarball
        run: |
          src/build.sh

      - name: Create release
        uses: actions/github-script@v6
        id: my-script
        with:
          result-encoding: string
          script: |
            github.rest.repos.createRelease({
              owner: "${{ github.repository_owner }}",
              repo: "${{ github.event.repository.name }}",
              tag_name: "v${{ github.ref_name }}",
              name: "${{ github.event.repository.name }} ${{ github.ref_name }}",
              target_commitish: "${{ github.sha }}",
              body: ""
            });
