on:  
  push:
    tags: ["*"]
  pull_request: 
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create release
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const tag = context.ref.replace(/refs\/(tags|pull)\//, "");
            const result = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `v${tag}`,
              name: `${context.repo.repo} ${tag}`,
              target_commitish: context.sha,
              body: ""
            });
            console.log(result.data);

  upload: 
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build tarball
        run: |
          src/build.sh

        # ref: https://til.simonwillison.net/github-actions/attach-generated-file-to-release
      - name: Upload tarball
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const fs = require("fs");
            const tag = context.ref.replace(/refs\/(tags|pull)\//, "");
            // Get release for this tag
            const info = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag
            };
            console.log(info)
            const release = await github.repos.getReleaseByTag(info);
            console.log(release.data);
            // Upload the release asset
            // await github.repos.uploadReleaseAsset({
            //   owner: context.repo.owner,
            //   repo: context.repo.repo,
            //   release_id: release.data.id,
            //   name: "app.zip",
            //   data: await fs.readFileSync("app.zip")
            // });          