on:  
  push:
    tags: ["*"]
  pull_request: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build tarball
        run: |
          src/build.sh

      - name: Create release
        uses: actions/github-script
        id: my-script
        with:
          result-encoding: string
          script: return "I will be string (not JSON) encoded!"
